### ISSUE TITLE
No RC to ground filtering on headphone lines

### ISSUE THREAD

**Issue by DanKoloff** [rasteri/SC1000#4]
Hello,

Lub from Olimex here. In your schematic I can see that there are no RC to ground groups on HPCOM and HPOUTL and HPOUTR. This might cause issues with some headphones or other audio equipment. Did you omit such on purpose?

Please perform some tests. Use the A13-OLinuXino-WIFI design as basis of the groups (left side of the schematic): https://github.com/OLIMEX/OLINUXINO/blob/master/HARDWARE/A13-OLinuXino/A13-OLinuXino_WIFI_Rev_H.pdf

I've also cut it out here: 
![audio-excerpt](https://user-images.githubusercontent.com/6028552/59090133-92fe4780-8914-11e9-81e0-f2b4c5273ee7.jpg)

Lub/OLIMEX

**Comment by rasteri** [comment]
Hi Lub, good to hear from you.

Yes this was an oversight, but this was just really a development board to test software etc. As you say, there is some noise on the headphone output, particularly when the device is unpowered. I'm doing a second board revision with these changes plus some other stuff (ESD protection, better capacitive touch sensing).

Thanks for your input - if you notice any other problems let me know.

**Comment by s3kn0tr0n1c** [comment]
Thanks for referring me to this after I contacted you about headphones out @DanKoloff .

I will modify my board this week as Im back from holiday and let you and @rasteri  know how it goes.

@rasteri  - Im the guy who you got to do the special firmware without touch sensor for. I have a couple of other minor issues that I'm sure you can fix too ;).

**Comment by s3kn0tr0n1c** [comment]
Hi, Heres some of my current mods. Ive added the caps/resistors to output. Will check it out properly over next few days. See if there's any improvement plugging into line ins etc.  Here's a picture of mod you can refer others to if they want to see how I did it. Basically soldered a resistor to headphone pin, cap to resistor x3 . Then soldered 1 wire from nearby GND to all the caps.
-
![HP Filter out](https://user-images.githubusercontent.com/51992360/59856397-bdb5ba80-936e-11e9-90eb-51e4b9e0607f.jpg)

I also added an area for my USB battery to be held so that unit can be an "all in one" unit. Heres how I did this using PCB spacers- 


![IMAG0488](https://user-images.githubusercontent.com/51992360/59856583-20a75180-936f-11e9-8ada-870e64c7ce18.jpg)
![IMAG0486](https://user-images.githubusercontent.com/51992360/59856584-20a75180-936f-11e9-9eb8-71834a01b16b.jpg)
![IMAG0487](https://user-images.githubusercontent.com/51992360/59856586-20a75180-936f-11e9-9ccd-d654c2f21d39.jpg)

Also see this video showing battery mod.  - https://youtu.be/33W1NoMLeOI


After that I redone the side panels so finished item is like this - 

![IMAG0490](https://user-images.githubusercontent.com/51992360/59856657-459bc480-936f-11e9-948d-899a68d0516a.jpg)

Its now a nice little all in one unit self powered( a little thicker but no messy wires or USB battery hanging about) . All I gotta do is plug in headphones. Sweet.

**Comment by s3kn0tr0n1c** [comment]
Now onto bug you @rasteri ;) Heres some issues(remember I'm on the "no touch sensor build")

1) When I load a new sample there is a distortion noise until I move the platter. You also get this if you go outwith the sample start/end points. Its quite extreme lol. 

2) If you move the xfader to the cut in point. Like right  between off/on you get this weird effect where you are hearing the sample playing but robotic like. Im not sure if this has anything to do with my next issue, perhaps causing a bug. 

3) Sticker drift. My reason for no touch sensor was to preserve the samples position to red marker on record. After a few fast movements and going round a full turn etc the sample no longer is at same position when you rewind record.

4) Not reloading sample when you change to it. Its like the sample is still stored in memory from before and plays from this position. It would be much better if it was reset/reloaded to play from the start again.

If 3 and 4 were sorted then I would be able to move record to 12oclock. Load in new sample and the samples would always be at same position , as they are on a regular record. (or on seratos -"sticker lock" feature, which is great.)

Must say if you could get these last things sorted this toy is GODLIKE ;).

Also I just discovered if you cut a beat correctly it auto loops as well. Ive been chopping 8-32 bar loops and they play like any skratch looper. Brilliant. Love it.

**Comment by s3kn0tr0n1c** [comment]
Also I just used a standard ball bearing this time and hot melted it in place. Not sure if how well it will stay in place. Should be fine if i never sit on it lol. 

Anyways FYI - you get flanged bearings that would be better that I may switch to later-

https://www.ebay.co.uk/itm/PREMIUM-MODEL-BEARINGS-FLANGED-TYPE-2RS-ZZ/200709759794?var=&hash=item2ebb3be332&enc=AQADAAAC0FjVrDbVsZ8oH%2F8PNHtt9VX4%2Fw7FZcmMuqsX8uaFEduVdDgLTuw154WAS%2BqpsGMK45U8hOE5BJlaSiJkjYBBoJ%2FAI81Flmw0F8Hm8qRzaQ%2F01%2F%2B3N%2BB9qzMoBGdBng7qg9PMGjGWTmq2Is%2BiAQTa6tVXURL5jrZ2eCrta1fnL64gJhs%2FpxeTRxhlZntD3%2Fh4CTHD8TZoOcRzUOAZp1pZ2otMxhG8QIDd0ZcjJkcQwAqq4RsYOnin2jUUho0K6NAqlNvcA50eSnf%2FpSJ28b%2BllIbuWUrx6x6lrUwkkT4Bzbb23r0XGMXbLhoncrWB1BVjYUAKwYQPE3jNzRZmkV%2BpMOu1EROGEhhH8cXAWU3VORUHs4EqJ%2Fx5aDS5SWOjzNpasPVfi6MxsAl%2F7kJzFnyMh4Muy5GHke5EVmmOKU1qxR8g%2BSbzMy6dQtOCEmLnAulSTd5VjALiarXQ26MOPwVq7qBtPFsgv%2ByngaDSZaCAqVC9F2n%2FZ7tQOjk9SAuD%2FIkYGLTH70hOXzcsyDP68tDVLOES7%2BTytwxZhPwDyvHwZPznj0MhTazbY73pUbh7G3U4va4jFKmj6sFQF7brQQZGY0bg5ISMPfZ%2F6xTQYYojsafrXz6%2BavGFc%2BWZTDQIpvlX2deCmLasQhd1Uhwfwcy6%2BLbx%2BaZWMrv5twTBtkDeOBnArOU%2Fotn3wVP%2B9IQgNjwhqJ1ULMAoBhna1ZnSVL7c2FbokjB24TB1ZoNDkUconSzzXpBR%2FOTktsGHkkVq4erBODQRi4%2Bso1Gv8fkAeWhuhaWXDoH%2BF0NPnxN8WrskFuzjf3FsDrkfiG8XuYYfyaVygk3zMOQsyoMdE%2BW24FQGZtplSZVO2rlfjhdGCGAtDhJ1d%2FKcvTr6UQ6ShjrhKtfK0pOEsbW1lIpyb8zNWufgyU6wdq9WZQ6qOLFpdy5EklMyA%2Ff9XLEhH5aWSjJCqk8gig%3D%3D&checksum=20070975979478113524aeb342f697389000ae930029

These would also be easier to get to sit perfectly flat. Worth thinking about for future build guides ;)

**Comment by s3kn0tr0n1c** [comment]
Ive did a video showing the bugs -

https://youtu.be/wtL78jQTReM

**Comment by rasteri** [comment]
I have updated the schematics and gerbers to include the filters, and designed a mod board so this can be retro-fitted to the original dev boards.

The latest firmware rev also fixes the issues s3kn0tr0n1c talked about - available here
[sc1000previewbuild.zip](https://github.com/rasteri/SC1000/files/3591641/sc1000previewbuild.zip)
